apiVersion: v1
kind: Secret
metadata:
  name: waps-construction-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.0.0
    app.kubernetes.io/instance: waps-construction
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "UnNWeGpaek1mcQ=="
  mariadb-password: "dVJZcFZ6T2pFSw=="
