kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: waps-construction-wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-14.0.0
    app.kubernetes.io/instance: waps-construction
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
